name: Generate Pac-Man Contribution Graph

on:
  schedule:
    # 毎日、日本時間9:00に実行
    - cron: "0 0 * * *"

  # Actions画面から手動実行
  workflow_dispatch:

  # mainブランチへのpush時にも実行
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: write

    steps:
      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: remon-nomer66

      - name: Publish generated SVG files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
